package presentation;

import visualization.GanttEntry;
import java.util.List;

/**
 * Renders the execution timeline of the CPU scheduling simulation in a clean ASCII format.
 * 
 * It consumes raw GanttEntry objects generated by the SimulationEngine and renders them
 * perfectly aligned, completely decoupling presentation logic from core execution logic.
 */
public class ConsoleTimelineRenderer {

    // The fixed character width of each rendered execution block
    private static final int BLOCK_WIDTH = 10;

    /**
     * Prints the chronological timeline of process execution.
     * 
     * @param chart The list of Gantt entries generated by the simulation.
     */
    public void render(List<GanttEntry> chart) {
        if (chart == null || chart.isEmpty()) {
            System.out.println("No execution data to render.");
            return;
        }

        StringBuilder timeLine = new StringBuilder();
        StringBuilder cpuLine = new StringBuilder();

        // 1. Initial time marker
        int firstTime = chart.get(0).getStartTime();
        timeLine.append(padWithDashes(firstTime, BLOCK_WIDTH));

        // 2. Build the timeline and CPU blocks dynamically
        for (int i = 0; i < chart.size(); i++) {
            GanttEntry entry = chart.get(i);
            
            // Format CPU Block to be exactly BLOCK_WIDTH characters long
            // e.g. "| P1       " (assuming BLOCK_WIDTH = 10)
            String processId = entry.getProcessId();
            String block = String.format("| %-" + (BLOCK_WIDTH - 2) + "s", processId);
            cpuLine.append(block);
            
            // Format Time Marker
            if (i == chart.size() - 1) {
                // The very last time marker does not need trailing dashes
                timeLine.append(entry.getEndTime()); 
            } else {
                timeLine.append(padWithDashes(entry.getEndTime(), BLOCK_WIDTH));
            }
        }
        
        // Close the final CPU block
        cpuLine.append("|");

        // 3. Render
        System.out.println("Time");
        System.out.println(timeLine.toString());
        System.out.println("CPU");
        System.out.println(cpuLine.toString());
    }

    /**
     * Pads a numeric time value with trailing dashes to ensure strict vertical alignment
     * between the timeline numbers and the CPU execution block dividers.
     */
    private String padWithDashes(int number, int totalWidth) {
        String numStr = String.valueOf(number);
        int dashesNeeded = totalWidth - numStr.length();
        
        if (dashesNeeded <= 0) {
            return numStr;
        }
        
        StringBuilder sb = new StringBuilder(numStr);
        for (int i = 0; i < dashesNeeded; i++) {
            sb.append("-");
        }
        return sb.toString();
    }
}
