package simulation;

import metrics.MetricsCalculator;
import metrics.MetricsReport;
import model.Process;
import scheduler.Scheduler;
import scheduler.SchedulerFactory;
import visualization.GanttEntry;
import simulation.SchedulingContext;

import java.util.Collections;
import java.util.List;

/**
 * The core orchestrator of the Schedulix framework.
 * 
 * It is purely responsible for taking a SimulationRequest, executing the appropriate
 * scheduling algorithm, delegating metrics calculation, and packaging the 
 * results into an immutable SimulationResult. It contains no business logic.
 */
public class SimulationEngine {

    /**
     * Executes the scheduling simulation based on the provided request.
     * 
     * @param request The encapsulated input parameters for the simulation.
     * @return A SimulationResult containing the final state, metrics, and visualization data.
     */
    public SimulationResult run(SimulationRequest request) {
        if (request == null) {
            throw new IllegalArgumentException("SimulationRequest cannot be null.");
        }

        List<Process> processes = request.getProcesses();

        // 1. Obtain the correct Scheduler using the Factory
        Scheduler scheduler = SchedulerFactory.create(request.getAlgorithmType());

        // 2. Prepare Context
        SchedulingContext context = new SchedulingContext(request.getTimeQuantum());
        for (Process p : processes) {
            context.enqueueProcess(p);
        }

        // 3. Execute the algorithm
        scheduler.schedule(context);

        // 4. Extract Gantt entries generated by the scheduler
        List<GanttEntry> ganttChart = context.getGanttEntries();

        // 4. Invoke MetricsCalculator to generate the report in a single API call
        MetricsReport report = MetricsCalculator.generateReport(processes);

        // 5. Construct and return the final result
        return new SimulationResult(
                request.getAlgorithmType(),
                processes,
                ganttChart,
                report
        );
    }
}
